= 子網路映射
:allow-uri-read: 




=== 子網路映射

在此版本中，您可以使用子網路對應以新的方式管理故障轉移時的 IP 位址，這使您能夠為每個 vCenter 新增子網路。當您這樣做時，您需要為每個虛擬網路定義 IPv4 CIDR、預設閘道和 DNS。

故障轉移時， NetApp Disaster Recovery 透過檢視為映射的虛擬網路提供的 CIDR 來確定每個 vNIC 的適當 IP 位址，並使用它來衍生新的 IP 位址。

例如：

* 網路A = 10.1.1.0/24
* 網路B = 192.168.1.0/24


VM1 有一個連接到 NetworkA 的 vNIC（10.1.1.50）。在複製計劃設定中，NetworkA 會對應到 NetworkB。

故障轉移時， NetApp Disaster Recovery 會取代原始 IP 位址 (10.1.1) 的網路部分，並保留原始 IP 位址 (10.1.1.50) 的主機位址 (.50)。對於 VM1， NetApp災難復原檢視 NetworkB 的 CIDR 設置，並使用 NetworkB 網路部分 192.168.1，同時保留主機部分 (.50) 來為 VM1 建立新的 IP 位址。新的IP變成192.168.1.50。

總之，主機位址保持不變，而網路位址則被網站子網路對映中所配置的位址取代。這使您能夠更輕鬆地管理故障轉移時的 IP 位址重新分配，特別是當您需要管理數百個網路和數千個虛擬機器時。

有關在站點中包含子網映射的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["新增 vCenter 伺服器站點"]。



=== 跳過保護

現在您可以跳過保護，以便服務在複製計劃故障轉移後不會自動建立反向保護關係。如果您想在NetApp災難復原中將復原的網站還原上線之前對其執行其他操作，這將非常有用。

當您啟動故障轉移時，如果原始來源網站處於線上狀態，則預設服務會自動為複製計畫中的每個磁碟區建立反向保護關係。這意味著該服務會建立從目標網站到來源網站的SnapMirror關係。當您啟動故障恢復時，該服務也會自動逆轉SnapMirror關係。

啟動故障轉移時，您現在可以選擇“跳過保護”選項。這樣，服務就不會自動逆轉SnapMirror關係。相反，它將可寫卷留在複製計劃的兩側。

原始來源網站恢復上線後，您可以從複製計畫操作選單中選擇*保護資源*來建立反向保護。這會嘗試為計劃中的每個磁碟區建立反向複製關係。您可以重複執行此作業，直到恢復保護。當保護恢復後，您可以按照通常的方式啟動故障恢復。

有關跳過保護的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["將應用程式故障轉移到遠端站點"]。



=== 複製計劃中的SnapMirror計劃更新

NetApp災難復原現在支援使用外部快照管理解決方案，例如本機ONTAP SnapMirror策略調度程式或與ONTAP 的第三方整合。如果複製計畫中的每個資料儲存庫（磁碟區）已經具有在其他地方管理的SnapMirror關係，則可以將這些快照用作NetApp災難復原中的復原點。

若要進行配置，請在複製計畫 > 資源映射部分中，在配置資料儲存映射時選取 *使用平台管理的備份和保留計畫* 複選框。

選擇選項後， NetApp Disaster Recovery 不會配置備份計畫。但是，您仍然需要配置保留計劃，因為仍可能需要拍攝快照以進行測試、故障轉移和故障回復操作。

配置完成後，服務不會定期拍攝任何快照，而是依賴外部實體來拍攝和更新這些快照。

有關在複製計劃中使用外部快照解決方案的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["建立複製計劃"]。
