---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter,amazon elastic vmware service 
summary: 使用 Amazon EVS 和Amazon FSx for NetApp ONTAP介紹NetApp災難復原。 NetApp災難復原是一種授權產品，必須先購買才能使用。有多種類型的許可證，您可以透過多種方式購買許可證。 
---
= 將NetApp災難復原服務​​新增至您的 Amazon EVS NetApp控制台帳戶
:allow-uri-read: 


[role="lead"]
NetApp災難復原是一種授權產品，必須先購買才能使用。有多種類型的許可證，您可以透過多種方式購買許可證。許可證授權您在特定時間內保護特定數量的資料。

有關NetApp災難復原許可證的更多信息，請參閱link:../get-started/dr-licensing.html["設定NetApp災難復原許可"]。



== 許可證類型

有兩種主要的許可證類型：

* NetApp提供link:../get-started/dr-licensing.html["30天試用許可證"]您可以使用它來評估使用ONTAP和 VMware 資源的NetApp災難復原。此許可證提供 30 天的使用期限，不受限制地使用受保護的容量。
* 如果您希望在 30 天試用期之後獲得 DR 保護，請購買生產許可證。您可以透過任何 NetApp 雲端合作夥伴的市場購買此許可證，但對於本指南，我們建議您使用 Amazon AWS Marketplace 購買NetApp Disaster Recovery 的市場授權。要了解有關透過 Amazon Marketplace 購買許可證的更多信息，請參閱link:../get-started/dr-licensing.html["透過 AWS Marketplace 訂閱"]。




== 確定災難復原容量需求

在購買許可證之前，您應該了解需要保護多少ONTAP儲存容量。使用NetApp ONTAP儲存的優點之一是NetApp儲存資料的效率很高。  ONTAP磁碟區中儲存的所有資料（例如託管虛擬機器的 VMware 資料儲存區）都是以高效率的方式儲存的資料。 ONTAP在將資料寫入實體儲存時預設採用三種儲存效率：壓縮、重複資料刪除和壓縮。最終結果是儲存效率在 1.5:1 到 4:1 之間，具體取決於所儲存的資料類型。事實上， NetApp提供了 https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["儲存效率保證"^]對於某些工作負載。

這對您有利，因為在應用所有ONTAP儲存效率之後， NetApp Disaster Recovery 會計算授權容量。例如，假設您在 vCenter 中設定了一個 100 TB (TiB) NFS 資料儲存區來託管您想要使用該服務保護的 100 台虛擬機器。此外，假設當資料寫入ONTAP磁碟區時，自動應用的儲存效率技術會導致這些虛擬機器僅消耗 33TiB（3：1 的儲存效率）。 NetApp災難復原只需要 33TiB 的許可，而不是 100TiB。與其他 DR 解決方案相比，這對於您的 DR 解決方案的整體擁有成本來說是一個非常大的好處。

.步驟
. 若要確定託管要保護的 VMware 資料儲存庫的每個磁碟區上消耗的資料量，請透過對每個磁碟區執行ONTAP CLI 命令來確定磁碟容量消耗： `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` 。
+
例如：

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. 注意每個磁碟區的“總物理使用量”值。這是NetApp災難復原需要保護的資料量，也是您將用來決定需要許可多少容量的值。

