---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: NetApp Console 代理負責協調 NetApp Console 與雲端或本地端儲存資源之間的連線與管理。 
---
= 安裝用於NetApp Disaster Recovery的NetApp Console代理
:allow-uri-read: 


[role="lead"]
NetApp Console 代理程式可讓您將 NetApp Console 部署連接到基礎架構，從而安全地協調跨 AWS、Azure、Google Cloud 或內部部署環境的解決方案。Console 代理程式會執行 NetApp Console 管理資料基礎架構所需的操作。Console 代理程式會持續輪詢 NetApp Disaster Recovery 軟體即服務層，以取得所需的任何操作。

對於災難恢復，這些行動會使用各服務的原生 API 來協調 VMware vCenter 叢集與 ONTAP 儲存設備執行個體，為在內部部署位置執行的正式作業 VM 提供保護。雖然 Console 代理程式可以安裝在您的任何網路位置，但我們建議將 Console 代理程式安裝在災難恢復站台以進行災難恢復。安裝在災難恢復站台可確保在主要站台發生故障時，NetApp 主控台 UI 能維持其與 Console 代理程式的連線，並能協調該災難恢復站台內的恢復程序。



[[installation]]
== 安裝

* 若要使用 Disaster Recovery，請以標準模式安裝 Console 代理程式。若要深入瞭解 Console 代理程式安裝類型，請造訪 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["瞭解 NetApp Console 部署模式"^]。


Console 代理程式的特定安裝步驟取決於您的部署類型。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["了解控制台代理"^]。


TIP: 使用 Amazon AWS 安裝 Console 代理程式最簡單的方法是使用 AWS Marketplace。有關使用 AWS Marketplace 安裝 Console 代理程式的詳細資訊，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["從 AWS Marketplace 建立 Console 代理程式"^]。
