---
sidebar: sidebar 
permalink: reference/vcenter-privileges.html 
keywords: disaster recovery, bluexp, vcenter, 
summary: 'vCenter 帳戶必須具有一組最低限度的 vCenter 權限，以允許NetApp Disaster Recovery 執行其服務，例如註冊和取消註冊資料儲存庫、啟動和停止虛擬機器以及重新配置虛擬機器 (VM)。下表列出了NetApp災難復原與 vCenter 叢集連線所需的所有權限。' 
---
= NetApp災難復原所需的 vCenter 權限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
vCenter 帳戶必須具有一組最低限度的 vCenter 權限，以允許NetApp Disaster Recovery 執行其服務，例如註冊和取消註冊資料儲存庫、啟動和停止虛擬機器以及重新配置虛擬機器 (VM)。下表列出了NetApp災難復原與 vCenter 叢集連線所需的所有權限。

[cols="25,35a,40a"]
|===
| 類型 | 權限名稱 | 描述 


| *資料儲存*  a| 
資料儲存.配置資料存儲
 a| 
用於配置資料儲存。



|   a| 
資料存儲. 刪除資料存儲
 a| 
用於刪除資料儲存。



| 虛擬機  a| 
虛擬機器. 配置. 更改設定
 a| 
用於變更常規 VM 設定。



|   a| 
虛擬機器. 配置. 修改設備設定
 a| 
用於更改現有設備的屬性。



|   a| 
虛擬機器.配置.從路徑重新載入
 a| 
用於變更 VM 配置補丁，同時保留 VM 的身份。  VMware vCenter Site Recovery Manager 等解決方案使用此操作在故障轉移和故障復原期間維護 VM 識別碼。



|   a| 
虛擬機器. 配置. 重新命名
 a| 
用於重新命名虛擬機器或修改虛擬機器的關聯節點。



|   a| 
虛擬機器. 配置. 重置客戶機資訊
 a| 
用於編輯 VM 的客戶作業系統資訊。



|   a| 
虛擬機器. 配置. 更改記憶體
 a| 
用於更改分配給 VM 的記憶體量。



|   a| 
虛擬機器. 配置. 更改 CPU 數量
 a| 
用於更改虛擬 CPU 的數量。



| *虛擬機器客戶機*  a| 
虛擬機器.客戶機操作.客戶機操作修改
 a| 
啟用涉及對 VM 中的客戶作業系統進行變更的 VM 客戶操作，例如將檔案傳輸到 VM。



| *虛擬機器互動*  a| 
虛擬機器.互動.關閉
 a| 
用於關閉已啟動的虛擬機器。此操作將關閉客戶作業系統。



|   a| 
虛擬機器.交互.開啟
 a| 
用於啟動已關閉的虛擬機器並復原已掛起的虛擬機器。



|   a| 
虛擬機器.互動.VMware Tools 安裝
 a| 
用於將 VMware Tools CD 安裝程式作為客戶作業系統的 CD-ROM 進行掛載和卸載。



| *虛擬機器清單*  a| 
虛擬機器. 清單. 新建
 a| 
用於建立虛擬機器並為其執行指派資源。



|   a| 
虛擬機器.庫存.註冊
 a| 
用於將現有 VM 新增至 vCenter Server 或主機清單。



|   a| 
虛擬機器. 清單. 取消註冊
 a| 
用於從 vCenter Server 或主機清單中取消註冊虛擬機器。



| *虛擬機器狀態*  a| 
虛擬機器. 快照管理. 建立快照
 a| 
用於從 VM 的目前狀態建立快照。



|   a| 
虛擬機器. 快照管理. 刪除快照
 a| 
用於從快照歷史記錄中刪除快照。



|   a| 
虛擬機器. 快照管理. 還原到快照
 a| 
用於將 VM 設定為給定快照時的狀態。

|===